<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'VerifyBlind\\Vendor\\phpseclib3\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'VerifyBlind\\Vendor\\ParagonIE\\ConstantTime\\' => array($vendorDir . '/paragonie/constant_time_encoding/src'),
);
